// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpNews.Data;

namespace SpNews.Migrations
{
    [DbContext(typeof(SpNewsContext))]
    [Migration("20220703100610_SeedDefaultDatatoCategoryMigration")]
    partial class SeedDefaultDatatoCategoryMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpNews.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "News related to foreign sports competitions",
                            Name = "Foreign"
                        },
                        new
                        {
                            Id = 2,
                            Description = "News about domestic competitions",
                            Name = "Domestic"
                        },
                        new
                        {
                            Id = 3,
                            Description = "News about football competitions",
                            Name = "Football"
                        },
                        new
                        {
                            Id = 4,
                            Description = "News about basketball competitions",
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 5,
                            Description = "News about volleyball competitions",
                            Name = "Volleyball"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
